### ISSUE TITLE
configuration for phantomjs

### ISSUE THREAD

**Issue by newtonianb** [gemini-testing/gemini#202]
The doc says to use this when using phantomjs

```
browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: phantomjs
```

What is the point of this? I don't have it in my config, I only have the gridUrl pointing to the phantomjs server and everything seems to work fine. (although) It seems my CSS has a glitch in whatever browser engine phantomjs uses. Is it possible to somehow use chrome engine with phantomjs?

My goal is to run the tests without my desktop being affected so phantomjs is perfect for that. I used the chrome driver it was a bit faster but I can't deal with my machine being locked up while the browser open and closes.
