### ISSUE TITLE
Cannot use plugins with the latest version

### ISSUE THREAD

**Issue by w0rm** [gemini-testing/gemini#224]
According to docs this should work:

```yml
system:
  plugins:
    some-awesome-plugin:
```

but plugins are still [loaded from the root](https://github.com/gemini-testing/gemini/blob/master/lib/plugins.js#L7).

if I write my config like this:

```yml
plugins:
  some-awesome-plugin:
```

then gemini complains `UnknownKeysError: Unknown options: root.plugins`.
