### ISSUE TITLE
Using Cookies

### ISSUE THREAD

**Issue by th3l0g4n** [gemini-testing/gemini#230]
Is it possible to specify cookie params (via yml file or programmatically) which are automatically injected into the SUT?
I would really like to give this project a try but our System heavily relies on this feature.

**Comment by sipayRT** [comment]
You can configure your Chrome browser by using `chromeOptions` param. For example, 

```
  chrome:
    desiredCapabilities:
      version: "48.0"
      browserName: chrome
      chromeOptions:
        prefs:
          profile:
            default_content_setting_values:
              geolocation: false
```

But not all browsers support it.
