### ISSUE TITLE
Documentation - Guidelines or best practices for covering multiple browsers and viewports

### ISSUE THREAD

**Issue by jenkinsw1** [gemini-testing/gemini#245]
Is it possible to document the best way to set up gemini to cover off multiple browsers and viewports?  Currently I have a very large config file that has separate 'browsers' entries for different browser/os combinations and different viewports within them, such as:

```
chromeWin7Medium:
    screenshotsDir: './screens/win7/chrome'
    windowSize: 641x1024
    desiredCapabilities:
        browserName: chrome
        platform: Windows 7

chromeWin7Large:
    screenshotsDir: './screens/win7/chrome'
    windowSize: 1025x1024
    desiredCapabilities:
        browserName: chrome
        platform: Windows 7

firefoxWin7Medium:
    screenshotsDir: './screens/win7/firefox'
    windowSize: 641x1024
    desiredCapabilities:
        browserName: firefox
        platform: Windows 7

firefoxWin7Large:
    screenshotsDir: './screens/win7/firefox'
    windowSize: 1025x1024
    desiredCapabilities:
        browserName: firefox
        platform: Windows 7

chromeMacMedium:
    screenshotsDir: './screens/mac/chrome'
    windowSize: 641x1024
    desiredCapabilities:
        browserName: chrome
        platform: Mac

chromeMacLarge:
    screenshotsDir: './screens/mac/chrome'
    windowSize: 1025x1024
    desiredCapabilities:
        browserName: chrome
        platform: Mac
```

It is a long list, especially as I am testing against 4 different viewport sizes for each browser/os combo.  I had a play around with sets in the hope that would allow me to define some defaults against specific browsers but gemini didn't seem to like getting given desiredCapabilities in that format.  Is that correct, or did I just set it up the wrong way?

This gives me a structure like:
-- screens
&nbsp;&nbsp;&nbsp;&nbsp;|-- mac
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- chrome
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- Buttons
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- NoAction (with 4 images, one per viewport size - small, medium, large, xlarge)
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- ClickedConfirmationButton
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- etc...
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- CallToActions
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- NoAction
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- etc...
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- firefox
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- Buttons
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- NoAction
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- etc...
&nbsp;&nbsp;&nbsp;&nbsp;|--win7
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- chrome
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;|-- etc...

So is there a more efficient way people have found to manage this kind of coverage? 

FYI - I am testing against a kitchensink that has all the different elements of our framework present, hence splitting the capture scripts down by element type.  This means we can be specific in running against changes as they get made.
