### ISSUE TITLE
Gemini not finding ID selector

### ISSUE THREAD

**Issue by CharlesBelov** [gemini-testing/gemini#383]
Gemini is not finding an ID selector that is on the page.

For .gemini.yml
```
rootUrl: http://www.sfmta.com
browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: phantomjs
```
and basic.js
```
var gemini = require('gemini');

gemini.suite('sfmta-home', function(suite) {
    suite.setUrl('/')
        .setCaptureElements('body')
        .capture('plain')
        .capture('with text', function(actions, find) {
            actions.sendKeys(find('#edit-search-block-form--2'), 'hello world');
        });
});
```
running the command `gemini update basic.js` returns
```
✓ sfmta-home plain [PhantomJS]
✘ sfmta-home with text [PhantomJS]
Could not find element with css selector in actions chain: #edit-search-block-form--2
```

The intended match is the following source code:
`<input title="Enter the terms you wish to search for." type="text" id="edit-search-block-form--2" name="search_block_form" value="" size="15" maxlength="128" class="form-text" />`
