### ISSUE TITLE
Error Out of Bounds

### ISSUE THREAD

**Issue by vpatton** [gemini-testing/gemini#394]
I get this from time to time running my tests on saucelabs, mostly IE  9 - Edge

Output of `gemini --version`:
2.1.1
...

Contents of `.gemini.yml` file:

``` yaml
rootUrl: http://beerfridayautotest.cms.dealer.com
tolerance: 3
screenshotsDir: './screens'
windowSize: 1600x1080
sessionsPerBrowser: 5
suitesPerSession: 10
calibrate: true

browsers:
  IE-10:
    screenshotsDir: './screens/ie10-screens'
    desiredCapabilities:
      version: "10.0"
      browserName: 'internet explorer'
      platform: "Windows 8"
      screenResolution: "1280x1024"
      name: "IE10 BeerFriday"

  IE-9:
    screenshotsDir: './screens/ie-screens'
    desiredCapabilities:
      version: "9.0"
      browserName: 'internet explorer'
      platform: "Windows 7"
      screenResolution: "1280x1024"
      name: "IE9 BeerFriday"

  EdgeWin10:
    screenshotsDir: './screens/edge'
    desiredCapabilities:
      version: "20.10240"
      browserName: 'MicrosoftEdge'
      platform: "Windows 10"
      screenResolution: "1280x1024"
      name: "EdgeWin10 BeerFriday"

system:
  plugins:
    sauce:
      username:
      accessKey:
```

Test source code:

``` js
    gemini.suite('beerfridayautotest Inventory Search', function (el) {
        el.setCaptureElements('div.ddc-container.tabbed-widgets-group.tabbed-widgets-group-1.tabs-slide-direction-left')
        .capture('Inventory Search', function (actions, el){
            actions.waitForElementToShow('div.ddc-container.tabbed-widgets-group.tabbed-widgets-group-1.tabs-slide-direction-left', 5000)
        });
    });
```

Command used to run the test:

```
gemini test ./test/ -c sauce.yml --reporter html
```

Publically accessible URL of the page you are testing against:

https://beerfridayautotest.cms.dealer.com/

Result:
Error: Out of the bounds
    at Error (native)
    at module.exports.inherit.fill (/Users/van.patton/test-framework-gemini/node_modules/png-img/index.js:66:19)
    at module.exports.inherit.fill (/Users/van.patton/test-framework-gemini/node_modules/png-img/index.js:56:25)
    at clear (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/image.js:31:19)
    at /Users/van.patton/test-framework-gemini/node_modules/gemini/lib/capture-session.js:74:25
    at Array.forEach (native)
    at module.exports.inherit._cropImage (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/capture-session.js:73:33)
    at wrapper (/Users/van.patton/test-framework-gemini/node_modules/gemini/node_modules/lodash/index.js:3533:19)
    at _fulfilled (/Users/van.patton/test-framework-gemini/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/van.patton/test-framework-gemini/node_modules/q/q.js:863:30)
...

Expected behaviour:
Hopefully a screenshot
...
