### ISSUE TITLE
Failed to capture the element footer

### ISSUE THREAD

**Issue by alexpts** [gemini-testing/gemini#408]
Output of `gemini --version`: 2.1.1

...

Contents of `.gemini.yml` file:

```yaml
rootUrl: https://alexpts.ru
tolerance: 3.5

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome

sets:
  alexpts.ru:
    files:
      - ./test/
```

Test source code:

```js
var gemini = require('gemini');

gemini.suite('alexpts footer', function(suite) {

  suite
    .setUrl('/')
    .setCaptureElements('footer')
    .capture('footer');
});
```

Command used to run the test:

```
node_modules/.bin/gemini gather test
```

Publically accessible URL of the page you are testing against:

https://alexpts.ru

Result: https://www.dropbox.com/s/3jedo7ps3oitm2u/chrome.png?dl=0

...

Error:
Failed to capture the element because it is positioned outside of the captured body. Most probably you are trying to capture an absolute positioned element which does not make body height to expand. To fix this place a tall enough <div> on the page to make body expand.
Element position: 0, 2912; size: 2070, 92. Page screenshot size: 2100, 1514.
...

More info: https://github.com/bem/bem-forum-content-ru/issues/936
