### ISSUE TITLE
Add the ability to run the test using a proxy server

### ISSUE THREAD

**Issue by xaircore** [gemini-testing/gemini#495]
I have a number of tests which must be run via a proxy. To do this, run the server browser with proxy option. But at the moment, there is no possibility for a launch configuration from config and from the test

**Comment by xaircore** [comment]
@SevInf @eGavr @sipayRT How to look at a functional?

**Comment by sipayRT** [comment]
Can you explain more detailed what you mean? And add example, pls, how it should be look

**Comment by xaircore** [comment]
@sipayRT I want use browser proxy settings. In python webdriver, i can do this
```
options = webdriver.ChromeOptions()
options.add_argument("--proxy-server=http://blablalba.com:8080")
driver = webdriver.Chrome(chrome_options=options)
```
After that, on the grid starts the browser proxy settings in which I have
In config I think this should look like this:
```
system:
    proxy: http://blablalba.com:8080
```

**Comment by sipayRT** [comment]
you can do it from gemini config. For example, enable geolocation:

```
  chrome:
    desiredCapabilities:
      version: "48.0"
      browserName: chrome
      platform: LINUX
      chromeOptions:
        prefs:
          profile:
            default_content_setting_values:
              geolocation: true
```

So you can add any settings for browser by using `chromeOptions` option
