### ISSUE TITLE
iOS iPhone Simulator doesn't grab the right images

### ISSUE THREAD

**Issue by briazzi64** [gemini-testing/gemini#533]
I'm trying to run mobile Gemini tests on an actual mobile device, in this case the iPhone 6 simulator, and the images grabbed are not correct. They seem to be off by a number of pixels. Is this seems to be an issue because Safari isn't listed as a supported browse? What should we do for running tests on a mobile device? These tests work fine for desktop browsers, but not mobile ones.

**Gemini Version:** 4.4.0

**Contents of `.gemini.yml` file:**

```yaml
rootUrl: https://www.google.com/
calibrate: false
browsers:
  iphone:
    desiredCapabilities:
      appiumVersion: "1.5.3"
      deviceName: "iPhone 6 Plus Simulator"
      deviceOrientation: "portrait"
      platformVersion: "9.3"
      platformName: "iOS"
      browserName: "Safari"
system:
  debug: false
```

**Test source code:**

```js
/* globals gemini */
gemini.suite("gemini", function(parent) {
    gemini.suite("google search", function(child) {
        child.setUrl("#")
            .setCaptureElements("#main")
	        .before(function(actions, find) {
	            this.element = find("#main");
	        })
	        .capture("plain");
    });
});
```

**Command used to run the test:**

```
gemini update src/tests/gemini/google/gemini.js
```

**Publicly accessible URL of the page you are testing against:**

https://www.google.com/#

**Result:**

![iphone](https://cloud.githubusercontent.com/assets/9169076/17142811/7778a2d6-531f-11e6-9637-7231b724785f.png)

**Expected behaviour:**

A clean picture of the Google search box on mobile.

**Comment by sipayRT** [comment]
Hi. Unfortunately gemini doesn't support IOS devices yet. But you can try Android device

**Comment by briazzi64** [comment]
Is iOS in the roadmap? Are there significant issues preventing iOS and/or Safari support?

**Comment by briazzi64** [comment]
For a temporary work around we're going to set the windowSize on an individual browser so that we can fake it. Something like this in the yaml file.

```
iphone:
    desiredCapabilities:
      version: "51.0"
      platform: "OS X 10.11"
      browserName: "chrome"
      recordVideo: "false"
      windowSize: "375x667"
```

But windowSize is ignored. Can we set browser windowSize on a per browser basis in the yaml file or is my only option to set it in the gemini test file with actions.setWindowSize?

**Comment by sipayRT** [comment]
About config - you need to set `windowSize` option not in the `desiredCapabilities` section:
```
iphone:
    windowSize: "375x667" <-----
    desiredCapabilities:
      version: "51.0"
      platform: "OS X 10.11"
      browserName: "chrome"
      recordVideo: "false"
```

About IOS - is was problem with detecting of real viewport size. Your screenshot proves it. Also we have some problems with coverage on these devices.

**Comment by briazzi64** [comment]
Thanks a bunch for all the info and the help with the config setup. It's not ideal but I understand. This should suffice for the bulk of our testing though. Thanks!

**Comment by tiggamcskelly** [comment]
Hi,  Did anyone ever look at IOS implementation?  I'm trying to run tests through browserstack and, if I set the window size I see a 'Method not implemented error:

Below is my .yml

```
  iPhone7:
    windowSize: 750x1334
    compositeImage: true
    desiredCapabilities:
      device: 'iPhone 7'
      os_version: '10.3'
      real_mobile: true
```
Here is my error:
```
Cannot launch browser iPhone7:
[setWindowSize(750,1334)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Appium error: Method is not implemented.'
```

Sorry I understand this ticket is quite old, I was just enquiring, thanks :)
