### ISSUE TITLE
Is that possible to use screenshotMode: fullpage on ChromeDriver?

### ISSUE THREAD

**Issue by thybzi** [gemini-testing/gemini#557]
Trying to use Gemini via ChromeDriver for mobile emulation testing
I want to get full page screenshot

My current settings are the following:
```yml
browsers:
  mobile-320:
    desiredCapabilities:
      browserName: chrome
      chromeOptions:
        mobileEmulation:
          userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'
          deviceMetrics:
            width: 320
            height: 6000
            pixelRatio: 1
```

This variant doesn't fail, though makes screenshots not 6000px high, but my available screen area high

I tried adding `screenshotMode: fullpage`, which doesn't have any effect.

Combining `screenshotMode: fullpage` with `height: 568` (instead of 6000) leads to `out of bounds` exception.

Any idea how to make this work (and make fullscreen mobile screenshot)?
