### ISSUE TITLE
Setting Selenium Options 

### ISSUE THREAD

**Issue by nathagey** [gemini-testing/gemini#604]
I'm trying to turn off chrome's location services, where can I configure this?

https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options

```
autoAcceptAlerts: false
```

**Comment by sipayRT** [comment]
```
  chrome:
    desiredCapabilities:
      version: "48.0"
      browserName: chrome
      chromeOptions:
        prefs:
          profile:
            default_content_setting_values:
              geolocation: false
```
?
