### ISSUE TITLE
Gemini logs "Running Gemini tests on undefined" but works

### ISSUE THREAD

**Issue by f0rmat1k** [gemini-testing/gemini#607]
And it shows twice:
```
Running Gemini tests on undefined
Running Gemini tests on undefined
```

if i set up variable `gemini_root_url` it shows correctly.

Output of `gemini --version`:
4.7.1

Contents of `.gemini.yml` file:

```yaml
gridUrl: some/grid
calibrate: false
tolerance: 1.7
httpTimeout: 10000
sessionRequestTimeout: 60000
sessionsPerBrowser: 1
suitesPerSession: 100
retry: 3
windowSize: 1024x720

browsers:
    chrome-latest:
        desiredCapabilities:
            version: "48.0"
            browserName: chrome
            platform: LINUX
            chromeOptions:
                prefs:
                    browser:
                        # spellchecker в Chrome случайным образом срабатывает
                        # в инпутах, тем самым приводя к мигающим тестам
                        enable_spellchecking: false
#    yabro-latest:
#        desiredCapabilities:
#            version: "yandex-browser"
#            browserName: chrome
#            platform: LINUX
    firefox-latest:
        desiredCapabilities:
            version: "41.0"
            browserName: firefox
            platform: LINUX
    ie-11:
        desiredCapabilities:
            version: "11"
            browserName: internet explorer
            platform: WINDOWS
            ie.enableFullPageScreenshot: false
    # edge-latest:
    #     desiredCapabilities:
    #         version: "12"
    #         browserName: MicrosoftEdge
    #         platform: WINDOWS
#    mobile-ios:
#        desiredCapabilities:
#            version: "8.4"
#            browserName: iOS
    # mobile-andrioid:
    #     desiredCapabilities:
    #         version: "6.0"
    #         browserName: android

system:
    parallelLimit: 1
```
Command used to run the test:
```
gemini test "--root-url" "some/root" "y-checkbox/test/gemini.js" "y-link/test/gemini.js"
```
