### ISSUE TITLE
Default tolerance 2.3 doesn't seem enough for machine differences.

### ISSUE THREAD

**Issue by bruk1977** [gemini-testing/gemini#682]
`gemini --version`:
4.13.0
...

Contents of `.gemini.json` file:

```yaml
{
  "rootUrl": "http://devserver/",
  "screenshotsDir": "./vDiffScreens",
  "browsers": {
    "phantomjs": {
      "retry": 3,
      "desiredCapabilities": {
        "browserName": "phantomjs"
      }
    }
  },
  "httpTimeout": 25000,
  "sessionRequestTimeout": 120000,
  "system": {
    "parallelLimit": 4
  },
  "compositeImage": true
}

```

Test source code:

```js
gemini.suite(baseUrl', function(suite) {
    suite.setUrl('/releases/core/templates/components/menu/')
        .setCaptureElements('#unique-id-for-list-1')
        .capture('normal')
});
```

Command used to run the test:
gemini test ./uitests --reporter flat --reporter html
```
```

Result:
It passes on the local box, but fails on a build machine with a ![visual difference](https://cloud.githubusercontent.com/assets/5600937/20655256/bed66ccc-b4d5-11e6-9f0c-2320425a7110.PNG) that I can't tell why.

...

Expected behaviour:
I'm expecting the test to pass on the build machine. Looks like there is a small visual difference caused by running on different machines. 

Should I increase the tolerance? As per the [documentation](https://github.com/gemini-testing/gemini/blob/master/doc/config.md) increasing tolerance is not recommendable... Not sure what to do...any advice is really appreciated.

...
