### ISSUE TITLE
Flick action doesn't work with selenium server

### ISSUE THREAD

**Issue by ximiksergey** [gemini-testing/gemini#684]
Output of `gemini --version`: 4.13.0

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://localhost/cartis/
sessionRequestTimeout: 60000
screenshotsDir: './screens'
browsers:
  chrome-ios: 
    rootUrl: http://localhost/mobile/ios
    screenshotsDir: './screens/ios'
    desiredCapabilities:
      browserName: 'chrome'
      chromeOptions:
        mobileEmulation: 
          userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4'
          deviceMetrics: 
            width: 375
            height: 667
            pixelRatio: 1
system:
    plugins:
      json-reporter:
        reportFile: ./gemini/report.json
```

Test source code:

```js
gemini.suite('Testing', (suite) => {
    suite.setUrl('/')
        .capture('delete with swipe', (actions, find) => {    
            el = find('.swipeout:first-child');
            actions.flick({ x: 1000, y: 1000 }, 2, el);
        })
});
```

Command used to run the test:

```
gemini test --reporter html --reporter vflat
```

Result:
```
[flick({"ELEMENT":"11"},1000,1000,2)] Error response status: 13, UnknownError - An unknown server-side error occurred while processi
ng the command. Selenium error: java.util.HashMap cannot be cast to java.lang.String
```

Expected behaviour:
Swipe occurs instead of the error.
