### ISSUE TITLE
ignoreAntialiasing not work in ie10 screen shot 

### ISSUE THREAD

**Issue by bindoon** [gemini-testing/gemini#709]
Output of `gemini --version`: 4.13.0

...

Contents of `.gemini.yml` file:

```yaml
gridUrl: http://f2etest.alibaba-inc.com:4444/wd/hub
windowSize: 1200x1080
compositeImage: true
browsers:
  chrome:
    desiredCapabilities:
        browserName: chrome
        f2etest.userid: ued-ut
        f2etest.apiKey: ****
  firefox:
    desiredCapabilities:
        browserName: firefox
        f2etest.userid: ued-ut
        f2etest.apiKey: ****
  ie8:
    desiredCapabilities:
        version: '8' 
        browserName: internet explorer
        f2etest.userid: ued-ut
        f2etest.apiKey: ****
  ie9:
    desiredCapabilities:
        version: '9' 
        browserName: internet explorer
        f2etest.userid: ued-ut
        f2etest.apiKey: ****
  ie10:
    desiredCapabilities:
        version: '10'
        browserName: internet explorer
        f2etest.userid: ued-ut
        f2etest.apiKey: ****
```

Test source code:

```js
var waitTime = 500;

gemini.suite('autowidth', function(suite) {
    suite.setUrl('/docs/autowidth.html')
    .setCaptureElements('.example')
    .capture('plain', function(actions, find) {

    }); 
});

```

- ref
![ie10 ref](https://cloud.githubusercontent.com/assets/5189853/21512566/e13f6c56-cce9-11e6-97bc-8e234e4ea93d.png)

- current

![ie10 current](https://cloud.githubusercontent.com/assets/5189853/21512568/ed4f18c0-cce9-11e6-98e5-3cbc149c6779.png)

- diff

![ie10 diff](https://cloud.githubusercontent.com/assets/5189853/21512570/f29d97c0-cce9-11e6-94e4-dcdf72dc1d1a.png)
