### ISSUE TITLE
How can I workaround focused input failings?

### ISSUE THREAD

**Issue by limonte** [gemini-testing/gemini#725]
How can I workaround failing tests in cases like input autofocus? I mean a resulted screenshot could both **with** or **without** cursor and as far as I know we can't predict that:

Example with cursor:

![edge](https://cloud.githubusercontent.com/assets/6059356/22427464/f23eedf6-e70b-11e6-8554-e2edfb08537e.png)

Example without cursor:

![edge copy](https://cloud.githubusercontent.com/assets/6059356/22427474/fcf69438-e70b-11e6-8689-b39777ed32a9.png)

As you can see, the only difference is cursor and as a result, tests are failing unpredictably.

Output of `gemini --version`:

4.17.1

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://127.0.0.1:3000/test/visual
gridUrl: http://127.0.0.1:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    express:
      port: 3000
    sauce: true

browsers:
  edge:
    desiredCapabilities:
      browserName: "microsoftedge"
      version: "14"
      platform: "Windows 10"
```

Test source code:

```js
gemini.suite('vaadin-input', function(rootSuite) {

  rootSuite.setUrl('/');

  gemini.suite('visual-tests', function(suite) {
    suite
      .setCaptureElements('#visual-tests')
      .capture('visual-tests', {}, function(actions, find) {
        actions.wait(3000);
      });
  });

});
```

Command used to run the test:

```
gemini test test/visual
```

**Comment by frederikmartin** [comment]
I fixed this by calling `blur()` on the input element before capturing state:

```
gemini.suite('project', function (suite) {
    suite.setUrl('/')
        .setCaptureElements('body')
        .capture('plain', function (actions, find) {
            // Blur focus on input field to avoid FP because of blinking caret
            actions.executeJS(function (window) {
                window.document.querySelector('input[name="foo"]').blur();
            });
        });
});
```

**Comment by limonte** [comment]
I made a tricky workaround for the focused input:

```css
input#hidden-caret {
  font-size: 0;
  padding: 10px 100px;
}
```

This is the cross-browser solution to hide caret in focused input.
