### ISSUE TITLE
Advice on using sessionsPerBrowser option

### ISSUE THREAD

**Issue by jenkinsw1** [gemini-testing/gemini#730]
Output of `gemini --version`:
4.18.1

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://testing.etc.etc
gridUrl: http://10.10.10.10:4444/wd/hub

calibrate: false
sessionsPerBrowser: 5
compositeImage: true
retry: 1

browsers:
  # WINDOWS 7 CONFIG
    chromeWin7Small:
        screenshotsDir: './screens/win7/chrome'
        windowSize: 640x1024
        desiredCapabilities:
            browserName: chrome
            platform: Windows 7

    chromeWin7Medium:
        screenshotsDir: './screens/win7/chrome'
        windowSize: 641x1024
        desiredCapabilities:
            browserName: chrome
            platform: Windows 7

    chromeWin7Large:
        screenshotsDir: './screens/win7/chrome'
        windowSize: 1025x1024
        desiredCapabilities:
            browserName: chrome
            platform: VISTA

    chromeWin7XLarge:
        screenshotsDir: './screens/win7/chrome'
        windowSize: 1441x1024
        desiredCapabilities:
            browserName: chrome
            platform: Windows 7

```

Test source code:
**Buttons.js**
```js
let cssVersion = process.env.CSSVERSION;

gemini.suite('Buttons', (suite) => {
    suite.setUrl('/kitchensink?cssVersion=' + cssVersion)
        .setCaptureElements('.snk_buttons')

        //All buttons together, with no actions performed
        .capture('NoAction', (action) => {
            action.wait(250)
        });
```

**Breadcrumbs.js**
```js
let cssVersion = process.env.CSSVERSION;

gemini.suite('Breadcrumbs', (suite) => {
    suite.setUrl('/kitchensink?cssVersion=' + cssVersion)
        .setCaptureElements('.snk_breadcrumbs')

        //All breadcrumb levels together, with no actions performed
        .capture('NoAction', (action) => {
            action.wait(250)
        });
```

Command used to run the test:

```
CSSVERSION=1.0.1 ./node_modules/gemini/bin/gemini update *.js
```

Publically accessible URL of the page you are testing against:

http://

Result:
Only a single browser session is started at a time on the grid.
...

Expected behaviour:
I have started a Selenium Grid running with Selenium 3.0.1, using just the standard config on the node.  Both run on the same virtual machine, and I use the following commands to start the hub and node:
`java -jar selenium-server-standalone-3.0.1.jar -role hub`

`java -jar selenium-server-standalone-3.0.1.jar -role node`

This results in a node being connected to the hub with the default 5 instances of Chrome available.

As you can see above, in the .gemini.yml I have `sessionsPerBrowser` set to 5, and I was expecting to have 5 instances of Chrome opening in parallel and running the image gathering actions on the node.

Can anyone correct my understanding of how this should work?  My tests are taking a long time, particularly as the browser is closed and reopened each time as I need to specify a new `setCaptureElements` value for each test suite.
...
