### ISSUE TITLE
Some tests break randomly due to wrong screenshot offsets and subpixel issues

### ISSUE THREAD

**Issue by squidfunk** [gemini-testing/gemini#734]
I'm experiencing a strange problem when running regression tests on SauceLabs for my project [Material for MkDocs](https://github.com/squidfunk/mkdocs-material). I do not know whether it is related to Gemini or some webdriver issue. I create the reference screenshots on all browsers and then run regression tests in CI, and sometimes the offsets of the screenshots on Edge, Firefox and IE11 seem to be a little off which makes my tests fail. For example, a test report can be found here with tests that were green all the time and suddenly failed:

http://mkdocs-material.s3-website-us-east-1.amazonaws.com/squidfunk/mkdocs-material/526/526.4/index.html

Some examples:

Edge:

![edge-diff](https://cloud.githubusercontent.com/assets/932156/22881007/c9666628-f1e4-11e6-8803-b4cd52226aaa.png)

Firefox:

![firefox-diff](https://cloud.githubusercontent.com/assets/932156/22881017/d52ac53a-f1e4-11e6-8230-4ddf70a76376.png)

IE11:

![ie11-diff](https://cloud.githubusercontent.com/assets/932156/22881027/e11b169c-f1e4-11e6-8734-f1e29f2fd1df.png)

I already disabled the use of webfonts, so only system fonts are used, because I suspected some issues with that. Chrome seems to be fine all the time.

**Output of `gemini --version`**: 4.19.0

**Contents of `.gemini.yml` file**:

``` yaml
{
  "rootUrl": "http://localhost:8000",
  "gridUrl": "http://ondemand.saucelabs.com/wd/hub",
  "screenshotsDir": "./tests/visual/baseline/ci",
  "browsers": {
    "chrome": {
      "desiredCapabilities": {
        "browserName": "chrome",
        "platform": "Windows 10",
        "screenResolution": "1280x1024",
        "recordVideo": "false"
      }
    },
    "firefox": {
      "desiredCapabilities": {
        "browserName": "firefox",
        "version": "47.0",
        "platform": "Windows 10",
        "screenResolution": "1280x1024",
        "recordVideo": "false"
      }
    },
    "edge": {
      "desiredCapabilities": {
        "browserName": "MicrosoftEdge",
        "platform": "Windows 10",
        "screenResolution": "1280x1024",
        "recordVideo": "false",
        "tolerance": 3.5
      }
    },
    "ie11": {
      "desiredCapabilities": {
        "browserName": "internet explorer",
        "version": "11.103",
        "platform": "Windows 10",
        "screenResolution": "1280x1024",
        "recordVideo": "false"
      }
    }
  },
  "system": {
    "projectRoot": ".",
    "sourceRoot": "./tests/visual/data",
    "coverage": {
      "enabled": false
    }
  }
}
```

**Command used to run the test**: The tests are run through the programmatic API
