### ISSUE TITLE
nothing happens - screen is simply green

### ISSUE THREAD

**Issue by GuyMograbi** [gemini-testing/gemini#750]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`:
4.18.1
...

Contents of `.gemini.yml` file:

```yaml
module.exports = {
  rootUrl: process.env.BASE_URL || 'http://localhost:9090',
  gridUrl: 'http://127.0.0.1:4444/wd/hub',
  screenshotsDir: 'tests/gemini/screens',
  tolerance: 0,
  browsers: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome'
      }
    }
  },
  // browsers,
  sets: {
    sanity: {
      files: ['tests/gemini/**/*.gemini.js'],

    }
  }
};
```

Test source code:

```js

gemini.suite('beta-page', (suite) => {
  const url = `/beta.html`;
  console.log('url is [', url, ']');
  suite.setUrl(url)
    .setCaptureElements('body')
    .capture(`beta`, (actions) => {
      actions.wait(5000);
    });
});


```

Command used to run the test:

```
gemini update
```

Publically accessible URL of the page you are testing against:

http://myhippo.com/beta.html

Result:

Nothing happens. The screen remains green. 

Expected behaviour:

The test should run
