### ISSUE TITLE
Critical error when coverage is enabled

### ISSUE THREAD

**Issue by apsavin** [gemini-testing/gemini#755]
Output of `gemini --version`:

4.18.1

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://localhost:3001
gridUrl: http://127.0.0.1:4444/wd/hub
browsers:
    chrome:
        desiredCapabilities:
            browserName: chrome

system:
  projectRoot: ../react-starter-kit
  sourceRoot: ./src
  exclude:
    - node_modules/**
  debug: true
  parallelLimit: 3
  diffColor: '#ff0000'
  coverage:
    enabled: true
    html: false
```

Test source code:

```js
gemini.suite('RSK', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('.test-header')
        .capture('plain');
});
```

Command used to run the test:

```
./node_modules/.bin/gemini test
```

You can reproduce [here](https://github.com/apsavin/react-starter-kit/tree/gemini)

Result:

```
...
Total: 1 Passed: 1 Failed: 0 Skipped: 0 Retries: 0
Critical error:
Error: ENOENT: no such file or directory, open '/Users/savin/PhpstormProjects/react-starter-kit/src/null'
    at Error (native)
From previous event:
    at /Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/coverage.js:314:23
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at readUrlOrFile (/Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/coverage.js:313:15)
    at processCSS (/Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/coverage.js:102:16)
    at /Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/coverage.js:70:34
    at Array.map (native)
    at /Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/coverage.js:69:61
    at /Users/savin/PhpstormProjects/react-starter-kit/node_modules/fs-extra/lib/mkdirs/mkdirs.js:54:16
    at /Users/savin/PhpstormProjects/react-starter-kit/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at processStats (/Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/coverage.js:68:14)
    at Promise.resolve.then.then.then.then (/Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/runner/index.js:40:56)
From previous event:
    at TestsRunner.run (/Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/runner/index.js:40:14)
    at getTests.then (/Users/savin/PhpstormProjects/react-starter-kit/node_modules/gemini/lib/gemini.js:102:31)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

Expected behaviour:

No errors, coverage report instead
