### ISSUE TITLE
SetSize does not work for Chrome.

### ISSUE THREAD

**Issue by rogozinds** [gemini-testing/gemini#761]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

I'm setting setSize both in the test and in the config file, seems like it doesn't have any affect on Chrome.

Output of `gemini --version`:
4.18.1
...

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://127.0.0.1:8081
gridUrl: http://127.0.0.1:4444/wd/hub
screenshotsDir: ./test/visual/screens
windowSize: 1700, 800
system:
  plugins:
    polyserve:
      port: 8080
    sauce:
      username: usr
      accessKey: passphrase

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "54.0"
      platform: "Windows 10"

  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "47.0"
      platform: "Windows 10"
```

Test source code:

```js
gemini.suite('vaadin-board-demo', function(rootSuite) {

    gemini.suite('default', function(suite) {
        suite
            .setUrl('/index.html')
            .before(function (actions, find) {
                actions.setWindowSize(1700, 800);
            })
            .setCaptureElements('body')
            .capture('main', {}, function(actions, find) {
                actions.wait(5000);
            });
    });
});
```

Command used to run the test:

```
wct --plugin sauce test
```

Publically accessible URL of the page you are testing against:

No public URL

Result:

The screenshot for chrome is 1020x695 px, for Firefox 1688x700(everything is fine). 
...

Expected behaviour:
The screenshot for chrome is around 1700x800 px.
...
