### ISSUE TITLE
Critical error: a value must be a primitive type when overriding ctx

### ISSUE THREAD

**Issue by yzhang-myob** [gemini-testing/gemini#762]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`:

4.18.1

Contents of `.gemini.yml` file:

```yaml
rootUrl: https://my-url
gridUrl: https://ignore.local

desiredCapabilities:
  project: ids
  build: ui-regression-tests 1.0.0
  browserstack.debug: true
  acceptSslCerts: true
  os: Windows
  os_version: 10

system:
  debug: true
  exclude:
    - node_modules/**
    - bower_components/**
  plugins:
    browserstack:
      username:
      accessKey:
  coverage:
    enabled: false
  ctx:
    clientId: ''
    redirectUri: ''
    username: ''
    password: ''

browsers:
  chrome57:
      desiredCapabilities:
        browserName: "chrome"
        version: "57.0"
    
```

Test source code:

```js
(function(gemini) {
  gemini.suite('login', function(suite) {
    suite.setUrl('/account/login')
      .setCaptureElements('#features-container')
      .capture('load')
      .before(function(actions, find) {
        this.submitButton = find('button.btn-primary[type="submit"]');
      })
      .capture('fields validation message', function(actions, find) {
        actions.click(this.submitButton);
      })
      .capture('wrong password error message', function(actions, find) {
        console.log("dd " + gemini.ctx.username);
        actions.sendKeys(find('#UserName'), 'ivaliduser@test.com');
        actions.sendKeys(find('#Password'), 'invalid');

        actions.click(this.submitButton);
      });
  });
})(gemini);

```

Command used to run the test:

```
gemini test ui-regression-tests --system-ctx-username correct@y.com
```

Publically accessible URL of the page you are testing against:

http://

Result:

...

Expected behaviour:

should override system.ctx.username with the config value. but throws 
Critical error:
a value must be a primitive type

If I change correct@y.com to 2, everything works
