### ISSUE TITLE
Can't run default gemini example on mac

### ISSUE THREAD

**Issue by vsorrokin** [gemini-testing/gemini#763]
I use mac os 10.12.3 and have nodejs and npm installed.
I have run this successfully:
```
npm install -g gemini
npm install -g selenium-standalone
selenium-standalone install
```
And trying to run test with params provided below but that is not working. I can't find info about how to use gemini with different browsers including IE8+, Firefox, Opera on mac. Maybe that is not possible at all? Or maybe I need to install selenium-standalone with some specific config?

Output of `gemini --version`:

4.18.1

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://yandex.ru
gridUrl: http://localhost:4444/wd/hub
browsers:
  chrome33:
    browserName: chrome
    version: '33.0'
  opera12:
    browserName: opera
    version: '12.16'
  firefox25:
    browserName: firefox
    version: '25.0'
  ie9:
    browserName: internet explorer
    version: '9.0'
```

Test source code:

```js
gemini.suite('yandex-search', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('.home-logo')
        .capture('plain');
});
```

Command used to run the test:

```
selenium-standalone start
```
And in different console tab
```
gemini test --reporter flat --reporter html
```

Publically accessible URL of the page you are testing against:

http://yandex.ru

Result:
```
Critical error:
UnknownKeysError: Unknown options: .browsers.chrome33.browserName, .browsers.chrome33.version
```
Expected behaviour:

Successful running of test

**Comment by sipayRT** [comment]
hi. You have mistakes in your config. Example:

```
browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome
      version: "45.0"

  firefox:
    desiredCapabilities:
      browserName: firefox
      version: "39.0"
```

So all grid options for browser should be in the `desiredCapabilities` section
