### ISSUE TITLE
Wrong window size

### ISSUE THREAD

**Issue by epsiloneridani** [gemini-testing/gemini#765]
Output of `gemini --version`:
`4.18.1`

Contents of `.gemini.yml` file:

```yaml
rootUrl: <my website>

compositeImage: true
sessionsPerBrowser: 3
calibrate: false

browsers:

 chromeSelenium_SmallMin:
    windowSize: 768x800
    desiredCapabilities:
      browserName: chrome
      resolution: 768x800
      acceptSslCerts: true

  chromeSelenium_XXSmall:
    windowSize: 320x800
    desiredCapabilities:
      browserName: chrome
      resolution: 320x800
      acceptSslCerts: true

sets:
  general:

    files:
    - ./gemini/test-body.js

    browsers:
    - chromeSelenium_XXSmall
    - chromeSelenium_SmallMin

```

Test source code:

```js
gemini.suite('fullpage', (suite) => {
  suite.setUrl('/')
  .setCaptureElements('body')
  .capture('plain');
});
```

Command used to run the test:

terminal 1:
`$ selenium-standalone start`

terminal 2:
`$ gemini update`

Result:

I get **screenshots of wrong size**: `383px` wide and `743px` wide, 

Expected behaviour:

**I should get two screenshots of sizes**: `320px` wide and `768px` wide. 
I'm using **Selenium**. Whatever `windowSize` I set the screenshot size is **never exactly the size I set**. But I need precision to one pixel to be sure that website is looking fine on each CSS breakpoint I use. 

When using **PhantomJS** windowSize is working perfectly well, but I can't use it because of other issues, like sign in doesn't work, and on screenshot it cuts footer.
