### ISSUE TITLE
"Cannot find files by mask gemini" exception when running

### ISSUE THREAD

**Issue by rogozinds** [gemini-testing/gemini#766]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`:
4.19.2
Output of `node --version`:
v4.4.5
...
Contents of `.gemini.yml` file:

```yaml
rootUrl: http://127.0.0.2:8080
gridUrl: http://127.0.0.1:4444/wd/hub
screenshotsDir: ./test/visual/screens
windowSize: 1700x800
system:
  plugins:
    polyserve:
      port: 8080
      hostname: 127.0.0.2
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "54.0"
      platform: "Windows 10"

  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "47.0"
      platform: "Windows 10"
```

Test source code:

```js
gemini.suite('vaadin-board-demo', function(rootSuite) {

    gemini.suite('default', function(suite) {
        suite
            .setUrl('/index.html')
            .before(function (actions, find) {
                actions.setWindowSize(1700, 800);
            })
            .setCaptureElements('body')
            .capture('main', {}, function(actions, find) {
                actions.wait(5000);
            });
    });
});
```

Command used to run the test:

```
gemini test ./test/visual/screens
```

Result:
Critical error:
Error: Cannot find files by masks in sets
    at SetsBuilder._useFiles (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/gemini-core/lib/sets-builder/index.js:93:19)
    at /media/dmitrii/sources/protools/vaadin-board-demo/node_modules/gemini-core/lib/sets-builder/index.js:72:43
    at tryCatcher (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/media/dmitrii/sources/protools/vaadin-board-demo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

...

Expected behaviour:
No exception

There is similar issue with previous version, https://github.com/gemini-testing/gemini/issues/569
but no explanation, what was the reason, just "update fixed issue".
