### ISSUE TITLE
Programmatic API: test didn't get executed

### ISSUE THREAD

**Issue by ganlanyuan** [gemini-testing/gemini#821]
Output of `gemini --version`:
5.0.0-alpha.8

Contents of `.gemini.yml` file:

```yml
rootUrl: 'http://localhost:8888'
compositeImage: true

system:
  plugins:
    browserstack:
      username: xxx
      accessKey: xxx
    'html-reporter':
      enabled: true
      path: 'gemini/gemini-reports'
      errorsOnly: false
      baseHost: 'http://localhost:8888'
 
browsers:
  ie11:
    windowSize: 600x400
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
 
  chrome43:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '10'
      browserName: 'chrome'
      version: '43'

sets:
  desktop:
    files:
      - 'gemini/tests/desktop'
    browsers:
      - ie11
      - chrome43
```

Test source code:

```js
gemini.suite('jumbotron', (suite) => {
  suite.setUrl('/')
    .setCaptureElements('html')
    .capture('plain');
});
```
Gulpfile.js:
```js
const Gemini = require('gemini/api'),
      gemini = new Gemini('./.gemini.yml');

var collection = gemini.readTests();
// var collection = gemini.readTests('gemini/tests/desktop');

gulp.task('default', () => {

  // gemini.readTests()
  //   .done(function(collection) {
  //     collection.topLevelSuites().forEach(function(suite) {
  //       console.log(suite.name);
  //     });
  //   });

  // console.log() works as expected

  return gemini.test(collection);
});
```

Command used to run the test:
```
gulp
```

Publically accessible URL of the page you are testing against:

https://ganlanyuan.github.io/myCoolProject/

Result:
```
[22:49:22] Using gulpfile ~/Documents/xxx/gulpfile.js
[22:49:22] Starting 'default'...
Opening BrowserStack tunnel.
Closing BrowserStack tunnel.
Your HTML report is here: file:///Users/xxx/gemini/gemini-reports/index.html
[22:49:49] Finished 'default' after 27 s
```

Expected behaviour:
The test was expected to be executed, but did not.
With command line, `gemini test` works well.
