### ISSUE TITLE
Full page screenshot collapse on IE8

### ISSUE THREAD

**Issue by ganlanyuan** [gemini-testing/gemini#830]
Output of `gemini --version`:
Version: 5.0.0-alpha.9
Global: 5.0.0-alpha.8

Contents of `.gemini.yml` file:
```yaml
rootUrl: 'http://localhost:8888'
compositeImage: true
screenshotMode: 'fullpage'
sessionsPerBrowser: 3

system:
    browserstack: {}
    'html-reporter':
      enabled: true
      path: 'gemini/gemini-reports'
      errorsOnly: false
      baseHost: 'http://localhost:8888'
 
browsers:
  ie:
    windowSize: 600x10000
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '8'
 
  chromeSmall:
    windowSize: 400x1024
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '18'

  chromeMedium:
    windowSize: 768x1024
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '18'

  chromeLarge:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '18'

  firefox:
    windowSize: 1024x768
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'firefox'
      version: '4'

sets:
  desktop:
    files:
      - 'gemini/tests/desktop'
    browsers:
      - ie
      - chromeSmall
      - chromeMedium
      - chromeLarge
      - firefox
```

Test source code:
```js
gemini.suite('jumbotron', (suite) => {
  suite.setUrl('/')
    .setCaptureElements('body')
    .capture('plain');
});
```

Command used to run the test:
```
gemini update
```

Publically accessible URL of the page you are testing against:
https://ganlanyuan.github.io/myCoolProject/

Result:
Full page screenshot collapse on IE8.    
![alt text](https://raw.githubusercontent.com/ganlanyuan/myCoolProject/master/gemini/screens/jumbotron/plain/ie.png "ie8 full page screenshot")

Expected behaviour:
Full page screenshot without content overlapping.
