### ISSUE TITLE
Sometimes process doesn't terminate

### ISSUE THREAD

**Issue by AnnaBodrova** [gemini-testing/gemini#849]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`:

...5.0.0-alpha.10

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://xxx
compositeImage: true
sessionQuitTimeout: 5000
tolerance: 3.5

system:
  plugins:
    #browserstack:
      #username: xxx
      #accessKey: xx
    #html-reporter:
      #enabled: false
  babel:
      presets: [
            "react",
            "es2015"
          ]
      plugins: [
            "transform-runtime",
            "transform-object-rest-spread"
          ]
    #react:
      #webpackConfig: webpack.dev.js
      #hostname: 127.0.0.1
      #port: 3002
      #staticRoot: "./public"
      #cssFiles: ["./css/main.css"]

browsers:
  chrome:
    desiredCapabilities:
      #os: "LINUX"
      #os_version: "10"
      browserName: "chrome"
      #version: "60"
      #resolution: "1920x1200"

```

Test source code:

```gemini.suite('MainPage', function (parent) {
    

    gemini.suite('topPage', function (child) {

        child.setUrl('/')

            .setCaptureElements('.grid-12.header-wrapper-pc', '.grid-12.searcher', '.grid-12.search-results')
            .ignoreElements({every: '.search-results__card-count'})
            .capture('topPage-PC')
            .capture('topPage-mobile', function (actions) {
                actions.setWindowSize(375, 667);
            });
    });


    gemini.suite('tabs', function (child) {

        child.setUrl('/')
            .setCaptureElements('.tabs')
            .capture('tabs-PC')
            .capture('tabs-mobile', function (actions) {
                actions.setWindowSize(375, 667);
            });
    });

    gemini.suite('datePicker-suit', function (child) {

        child.setUrl('/')

            .setCaptureElements('label.input-holder.datepicker-holder div.icon-small.search svg use', '.datepicker-wrapper')
            .ignoreElements({every: '.month-year'}, {every: '.month-table'})

            .before(function (actions, find) {
                this.icon = find('label.input-holder.datepicker-holder div.icon-small.search svg use');
                actions.mouseMove(this.icon);
                actions.mouseDown(this.icon);
                actions.mouseUp(this.icon);
            })
            .capture('datapicker-PC')
            .capture('datapicker-mobile', function (actions) {
                actions.setWindowSize(375, 667);
            });

    });

});

```

Command used to run the test:

```npm run gemini test
npm run gemini update
```
node version v8.9.1, Ubuntu

Publically accessible URL of the page you are testing against:

http://no 

Result:

...Sometimes process doesnt terminate. It shows Total info and and doesn't stop. If execute timeout -k 23 3s npm run gemini test, it'll stop browser, and stop testing, but after showing total info process will not stop. 

Expected behaviour:

...
always terminate process
