### ISSUE TITLE
os.tmpDir() is deprecated and no diff generated

### ISSUE THREAD

**Issue by maxneaga** [gemini-testing/gemini#870]
Output of `gemini --version`: 5.2.1

Contents of `.gemini.yml` file:

```
rootUrl: http://oit-drupal-dev-07.oit.umn.edu/
gridUrl: http://127.0.0.1:4444/wd/hub

browsers:
    chrome:
        desiredCapabilities:
            browserName: chrome

```

Test source code:

```
gemini.suite('CSE Homepage', function(test) {
    test.setUrl('/');
    
    gemini.suite('UMN header', function(test) {
        test.setCaptureElements('#mandatory-header-wrapper')
            .capture('plain');
    });
    
    gemini.suite('College header', function(test) {
        test.setCaptureElements('#header')
            .capture('plain');
    });
    
});

```

Command used to run the test:

```
gemini-gui
```

**Result:**

When running tests via gemini-gui, and when I tweak CSS to make a test fail intentionally, gemini-gui reports as if everything is fine:
![image](https://user-images.githubusercontent.com/3027370/35300377-d4b774fe-004d-11e8-968d-7e6c7c953046.png)
while the terminal says the opposite and shows a failed test.
![image](https://user-images.githubusercontent.com/3027370/35300431-fa469d58-004d-11e8-8b71-6507f58c6cbf.png)

I believe this can be related to the deprecated errors for os.tmpDir()

I am using NodeJS version 8.9.1

**Expected behavior:**

gemini-gui must highlight "College header" in red and provide a diff of screenshots.

...
