### ISSUE TITLE
How to take fullpage screenshot

### ISSUE THREAD

**Issue by cgaulay** [gemini-testing/gemini#901]
Hi,

is there any way to capture the full page with gemini ? 
i've tried to do this but it doesn't work fine for me. There is just the viewport screen.
thanks in advance.
Regards,

Output of `gemini --version`:
5.6.2

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://XXXXX
gridUrl: http://localhost:4444/wd/hub
#windowSize: 1366x768
tolerance: 3.5
calibrate: false
httpTimeout: 5000
sessionRequestTimeout: 60000
sessionQuitTimeout: 5000
screenshotsDir: ./screens
screenshotDelay: 2000
browsers:
  firefox:
    desiredCapabilities:
      screenshotMode: fullpage
      browserName: firefox
      compositeImage: true
system:
  debug: true
```

Test source code:

```js
gemini.suite('test', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('body')
        .capture('plain');
});
```

Command used to run the test:

```
gemini update --reporter html test.js 
```

Result:
There is just the viewport screen

**Comment by Dmitriy-kiselyov** [comment]
Hello! It seems like you misunderstand option `screenshotDelay`. Your page has some elements, that appear with time, so you want to wait for them to appear before taking a screenshot. You have 2 common ways to achieve that:
1. use `actions.waitForElementToShow(selector, [timeout])` function in your `capture` block if you are waiting for some particular element
2. or use `actions.wait(milliseconds)` if there are many delayed elements
Read more [here](https://gemini-testing.github.io/doc/tests.html)

In you case I think you want to do something like this:
```js
gemini.suite('test', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('body')
        .capture('plain', (actions) => actions.wait(2000));
});
```
and remove `screenshotDelay` option.

<u>This should fix your problem</u>. Please report if it does and close issue.

*P.S.*
About `screenshotDelay`. For example your `body` can be captured by 4 screenshots. So if you use `screenshotDelay: 2000` then whole capture session will last for ≈8 seconds. But if you use `actions.wait(2000)`, capture session will wait for 2 seconds and then perform 4 screenshots with no interval, so session will last ≈2 seconds

**Comment by j0tunn** [comment]
@cgaulay 
There are some errors in your config. Instead of this:
```yaml
browsers:
  firefox:
    desiredCapabilities:
      screenshotMode: fullpage
      browserName: firefox
      compositeImage: true
```
you should write something like this:
```yaml
browsers:
  firefox:
    screenshotMode: fullpage
    compositeImage: true
    desiredCapabilities:
      browserName: firefox
```
`screenshotMode` and `compositeImage` are the browser options and not the desired capabilities. In fact you can omit `screenshotMode` option, it does nothing in your case.
