### ISSUE TITLE
`gemini  update`  leads to node crash when I ran test against Firefox

### ISSUE THREAD

**Issue by BorisOsipov** [gemini-testing/gemini#928]
`gemini  update` leads to node crash when I ran test against Firefox(in my case 61.0.1)
It works well when I use Chrome with the same setup.

OS:
```
bo@boubuntu:~/tmp/genimi$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artfu
```
Node version
```
bo@boubuntu:~/tmp/genimi$ node -v
v8.11.3
```

Output of `gemini --version`:

```
bo@boubuntu:~/tmp/genimi$ gemini --version
5.8.0
```

Contents of `.gemini.js` file:

```yaml
module.exports = {
    rootUrl: 'http://yandex.ru',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',

    browsers: {
        firefox: {
            desiredCapabilities: {
                browserName: 'firefox'
            }
        }
    }
};
```

Test source code:

```js
gemini.suite('yandex-search', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('.home-logo')
        .capture('plain');
});
```

Command used to run the test:

```
gemini update
```

Publically accessible URL of the page you are testing against:

http://yandex.ru

Result:

```
bo@boubuntu:~/tmp/genimi$ gemini update
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [node]
 2: 0x8c21ec [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: PngImgAdapter::NewInstance(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/bo/.nvm/versions/node/v8.11.3/lib/node_modules/gemini/node_modules/png-img/build/Release/png_img.node]
 5: 0x7f9074812065 [/home/bo/.nvm/versions/node/v8.11.3/lib/node_modules/gemini/node_modules/png-img/build/Release/png_img.node]
 6: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 7: 0xad762f [node]
 8: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 9: 0x3175155842fd
Aborted (core dumped)
```

Expected behaviour:

Not crashes.
