### ISSUE TITLE
Как игнорировать fixed header

### ISSUE THREAD

**Issue by Jarib4ik** [gemini-testing/gemini#950]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`:
7.0.1
...

Contents of `.gemini.yml` file:

```yaml
module.exports = {
    rootUrl: 'http://utkonos.ru',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',
    "windowSize" : "1920x1080",
    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
            }
        }
    },

    system: {
        plugins: {
            'html-reporter/gemini': {
                enabled: true,
                path: 'gemini-reports',
                defaultView: 'all',
                baseHost: ''
            }
        }
    },
};


```

Test source code:

```js
gemini.suite('MainText', (suite) => {
    suite.setUrl('/')
        .capture('')
        .setCaptureElements('div.module_login_promo_advantages-item')
        .ignoreElements('.module_search_field_white')
});


```

Command used to run the test:

```
gemini update / gemini test
```

Publically accessible URL of the page you are testing against:

http://utkonos.ru

Result:
Строка поиска из фиксированной шапки не игнорируется
...

Expected behaviour:
Строка поиска из фиксированной шапки игнорируется
...
