### ISSUE TITLE
How to use Gemini in azure build pipeline

### ISSUE THREAD

**Issue by InoshikaFernando** [gemini-testing/gemini#981]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`: 7.5.2

...

Contents of `.gemini.yml` file:

```yaml
rootUrl: https://www.nzme.co.nz
screenshotsDir: ./gemini/screens
browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: phantomjs
sets:
  ff:
    files:
     - ./home
    browsers:
     - PhantomJS
```

Test source code:

```js
gemini.suite('menu', (suite) => {
    suite.setUrl('/')
        .setCaptureElements(['.container-fluid', '.header_page' ])
        .capture('menu');
});

gemini.suite('body', (suite) => {
    suite.setUrl('/')
        .setCaptureElements(['.home-grid' ])
        .capture('body');
});

gemini.suite('footer', (suite) => {
    suite.setUrl('/')
        .setCaptureElements(['.footer_site_nav','.footer_copyright' ])
        .capture('footer');
});
```

Command used to run the test:

```
gemini update
gemini test
```

Publically accessible URL of the page you are testing against:

https://www.nzme.co.nz/

Result:Pass

...

Expected behaviour:Pass

...
This is not an issue. I just like to know how we can use gemini in azure pipeline
