### ISSUE TITLE
Failed in gemini update step

### ISSUE THREAD

**Issue by oldpistonaddicted** [gemini-testing/gemini#984]
Output of `gemini --version`: 7.5.2

...

Contents of `.gemini.js` file:

```yaml
module.exports = {
    rootUrl: 'http://yandex.ru',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }
    }
};
```

Test source code:

```js
gemini.suite('yandex-search', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('.home-logo')
        .capture('plain');
});
```

Command used to run the test:

```
gemini update
```

Publically accessible URL of the page you are testing against:

http://yandex.ru

Result:
/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/config/config-reader.js:23
        throw new GeminiError('No config found');
        ^

GeminiError: No config found
    at getDefaultConfig (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/config/config-reader.js:23:15)
    at Object.exports.read (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/config/config-reader.js:10:28)
    at readConfig (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/config/index.js:61:31)
    at new Config (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/config/index.js:28:18)
    at new Gemini (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/gemini.js:43:23)
    at mkGemini (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/cli/index.js:96:20)
    at Object.exports.run (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/lib/cli/index.js:23:20)
    at Object.<anonymous> (/Users/tester/.nvm/versions/node/v12.14.1/lib/node_modules/gemini/bin/gemini:33:25)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  name: 'GeminiError',
  advice: undefined
}

...

Expected behaviour:

...
